services:
  flask:
    container_name: score-to-midi-production
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always  # Restart in case of error.
    volumes:
    - ./logs:/var/log/gunicorn  # Volumen para logs en el host
    - ./data:/app/data  # Volumen para logs en el host